---
title: "Data Cleaning Experiment 1"
output:
  word_document: default
  pdf_document: default
---

```{r, echo=FALSE, include=FALSE, cache = FALSE}
#### Workspace setup ####
knitr::opts_chunk$set(echo = TRUE)
# install.packages("tidyverse")
# install.packages("janitor")
# install.packages("car")
library(tidyverse)
library(janitor)
library(car)
```

```{r, echo=TRUE, include=TRUE, cache = FALSE}
# import file from CSV
raw_data_1 <- read.csv("action-inaction-eoc-experiment-1-data.csv", header=TRUE, fileEncoding = "UTF-8-BOM") 

# calculate condition
raw_data_1$condition <- 0
for (i in 1:nrow(raw_data_1)){
  if (!is.na(raw_data_1$EOC1_me[i])) (raw_data_1$condition[i] <- 1)
  if (!is.na(raw_data_1$EOC1_other[i])) (raw_data_1$condition[i] <- 2)
  if (!is.na(raw_data_1$DEC1_me[i])) (raw_data_1$condition[i] <- 3)
  if (!is.na(raw_data_1$DEC1_other[i])) (raw_data_1$condition[i] <- 4)
}

# some recoding to get the condition
raw_data_1$blankeocdec<- recode(raw_data_1$condition, "c(1,2)=1;c(3,4)=2; else=NA")
raw_data_1$blankme<- recode(raw_data_1$condition, "c(1,3)=1;c(2,4)=2; else=NA")
raw_data_1$condition<-factor(raw_data_1$condition,levels = c(1,2,3,4), 
                          labels=c("Escalation-action / Self-initiated", 
                                   "Escalation-action / Other-initiated",
                                   "Deescalation-action / Self-initiated",
                                   "Deescalation-action / Other-initiated"))

#value labels
raw_data_1$blankeocdec<-factor(raw_data_1$blankeocdec,levels = c(1,2), labels=c("Escalation-action", "Deescalation-action"))
raw_data_1$blankme<-factor(raw_data_1$blankme,levels = c(1,2), labels=c("Self-initiated", "Other-initiated"))

# calcaulte attention checks for exclusions
raw_data_1$include<-(raw_data_1$blankeocdec=="Escalation-action" & raw_data_1$manchk2<=3) |
  (raw_data_1$blankeocdec=="Deescalation-action" & raw_data_1$manchk2>=3)

# including only those who passed the attention checks
raw_data_1<-subset(raw_data_1, include==1)

# the effects for the 'other initiated conditions' are stronger, but in this manuscript we focus on the 'self initiated' conditions.
raw_data_1<-subset(raw_data_1, blankme=="Self-initiated")
head(raw_data_1)

```

```{r}
# Clean data
cleaned_data_1 <-
  raw_data_1 |>
  select(
    blankeocdec,
    esc1
  )

cleaned_data_1 <-
  cleaned_data_1 |>
  rename(
    action_framing = blankeocdec,
    escalation_of_commitment = esc1
  )

head(cleaned_data_1)
```

```{r}
write_csv(
  x = cleaned_data_1,
  file = "cleaned_experiment_1_data.csv"
)
```

