---
title: "Data Cleaning Experiment 3"
author: "Based on Daniel Lakens's perfect t-test template"
output:
  word_document: default
  pdf_document: default
---

```{r, echo=FALSE, include=FALSE, cache = FALSE}
#### Workspace setup ####
knitr::opts_chunk$set(echo = TRUE)
# install.packages("tidyverse")
# install.packages("janitor")

library(tidyverse)
library(janitor)
```

```{r, echo=TRUE, include=TRUE, cache = FALSE}
# import file from CSV
raw_data_3 <- read.csv("action-inaction-eoc-experiment-3-data.csv", header=TRUE, fileEncoding = "UTF-8-BOM") 

# calculate condition
raw_data_3$condition <- 0
raw_data_3$escalation <- 0
for (i in 1:nrow(raw_data_3)){
  if (!is.na(raw_data_3$ai_int1[i])){
    raw_data_3$condition[i] <- 1
    raw_data_3$escalation[i] <- raw_data_3$ai_decision[i]
  }
  if (!is.na(raw_data_3$ia_int1[i])){
    raw_data_3$condition[i] <- 2
    raw_data_3$escalation[i] <- raw_data_3$ia_decision[i]
  }
  if (!is.na(raw_data_3$am_int1[i])){
    raw_data_3$condition[i] <- 3
    raw_data_3$escalation[i] <- raw_data_3$am_decision[i]
  }
}

#value labels
raw_data_3$condition<-factor(raw_data_3$condition,levels = c(1,2,3), labels=c("Escalation-action", "Deescalation-action", "Ambiguous"))
```

```{r}
# clean data
cleaned_data_3 <-
  raw_data_3 |>
  select(
    condition,
    escalation
  )

cleaned_data_3 <-
  cleaned_data_3 |>
  rename(
    action_framing = condition,
    escalation_of_commitment = escalation
  )

head(cleaned_data_3)
```

```{r}
write_csv(
  x = cleaned_data_3,
  file = "cleaned_experiment_3_data.csv"
)
```

